apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-client
  namespace: voip
  labels:
    component: kube-client
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kube-client
  template:
    metadata:
      labels:
        component: kube-client
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
      containers:
        - name: kube-client
          image: ghcr.io/voxoco/kube-client:latest
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: TZ
              value: America/Chicago
      imagePullSecrets:
        - name: regcred
